# Generated by Django 2.1 on 2019-08-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newstable',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('datetime_list', models.DateTimeField(blank=True, null=True)),
                ('news', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, choices=[('1', '美国'), ('2', '中国'), ('3', '欧洲'), ('4', '原油'), ('5', '日本'), ('6', '拉丁美洲'), ('7', '澳洲'), ('8', '其他')], max_length=3, null=True)),
                ('important', models.CharField(blank=True, choices=[('0', 'just for fun'), ('1', '不重要'), ('2', '一般'), ('3', '重要'), ('4', '十分重要'), ('9', '待定')], max_length=1, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('isDelete', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'newstable',
            },
        ),
    ]
